export const INPUT_CONFIGS = [
  {
    id: "energy_supply",
    heading: "Energy Supply",
    sliders: [
      {
        id: "coal",
        label: "Coal",
        min: -15,
        max: 100,
        unit: "$/ton",
        stateConfig: {
          "-15": "subsidized",
          "-5": "status quo",
          5: "taxed",
          15: "highly taxed",
          30: "very highy taxed",
        },
      },
      {
        id: "renewabled",
        label: "Renewabled",
        min: -0.05,
        step: 0.01,
        max: 0.02,
        unit: "$/kWh",
        stateConfig: {
          "-0.05": "highly subsidized",
          "-0.02": "subsidized",
          "-0.01": "status quo",
          0.01: "taxed",
        },
      },
      {
        id: "oil",
        label: "Oil",
        min: -15,
        max: 85,
        unit: "$/barrel",
        stateConfig: {
          "-15": "subsidized",
          "-5": "status quo",
          5: "taxed",
          15: "highly taxed",
          30: "very highy taxed",
        },
      },
      {
        id: "nuclear",
        label: "Nuclear",
        min: -0.07,
        step: 0.01,
        max: 0.07,
        unit: "$/kWh",
        stateConfig: {
          "-0.07": "highly subsidized",
          "-0.04": "subsidized",
          "-0.01": "status quo",
          0: "taxed",
          0.03: "highly taxed",
        },
      },
      {
        id: "natural_gas",
        label: "Natural Gas",
        min: -0.7,
        step: 0.1,
        max: 5,
        unit: "$/MCF",
        stateConfig: {
          "-0.7": "subsidized",
          "-0.2": "status quo",
          0.2: "taxed",
          0: "taxed",
          0.7: "highly taxed",
          1.4: "very highly taxed",
        },
      },
      {
        id: "new_zero_carbon_breakthrough",
        label: "New Zero-Carbon",
        min: 0,
        step: 1,
        max: 2,
        unit: "",
        stateConfig: {
          0: "status quo",
          1: "breakthrough",
          2: "huge breakthrough",
        },
      },
      {
        id: "bioenergy",
        label: "Bioenergy",
        min: -25,
        step: 1,
        max: 25,
        unit: "$/boe",
        stateConfig: {
          "-25": "highly subsidized",
          "-15": "subsidized",
          "-5": "status quo",
          5: "taxed",
          15: "highly taxed",
        },
      },
      {
        id: "carbon_price",
        label: "Carbon Price",
        min: 0,
        step: 1,
        max: 250,
        unit: "$/ton CO2",
        stateConfig: {
          0: "status quo",
          5: "low",
          20: "medium",
          60: "high",
          100: "very high",
        },
      },
    ],
  },
  {
    id: "transport",
    heading: "Transport",
    sliders: [
      {
        id: "enery_efficiency",
        label: "Enery Efficiency",
        min: -1,
        step: 0.1,
        max: 5,
        unit: "%/year",
        stateConfig: {
          "-1": "discouraged",
          0: "status quo",
          1: "increased",
          3: "highly increased",
        },
      },
      {
        id: "electrification",
        label: "Electrification",
        min: 0,
        step: 5,
        max: 50,
        unit: "% of purchase cost",
        stateConfig: {
          0: "status quo",
          10: "subsidized",
          25: "highly subsidized",
        },
      },
    ],
  },
  {
    id: "building_industry",
    heading: "Building and Industry",
    sliders: [
      {
        id: "enery_efficiency",
        label: "Enery Efficiency",
        min: -1,
        step: 0.1,
        max: 5,
        unit: "%/year",
        stateConfig: {
          "-1": "discouraged",
          0: "status quo",
          1.5: "increased",
          3: "highly increased",
        },
      },
      {
        id: "electrification",
        label: "Electrification",
        min: 0,
        step: 5,
        max: 50,
        unit: "% of purchase cost",
        stateConfig: {
          0: "status quo",
          5: "subsidized",
          25: "highly subsidized",
        },
      },
    ],
  },
];
